export NEW_CLI=1 
export MyTenant=xxxx.live.dynatrace.com
export MyToken=dt0c01.abcdefghij.abcdefghijklmn
export PaasToken=$MyToken
export list_user="user00@demo.com user01@demo.com"
export EnableSynthetic=false
export TIME=`date +%Y%m%d%H%M%S`
export DOMAIN_NAME_DEFAULT=demodomaine$TIME
export DOMAIN_NAME=$DOMAIN_NAME_DEFAULT
export PASSWORD=DummyP@ssword00
export SIZE_LINUX=Standard_B2ms #2 CPU 8 GB
#export SIZE_LINUX=Standard_B4ms #4CPU 16 GB
export SIZE_WINDOWS=Standard_B2ms   #2 CPU 8 GB
export LOCATION4=francecentral
export LOCATION1=westeurope
export LOCATION2=northeurope
export LOCATION3=uksouth
export LOCATION5=eastus #Reserved for the kubernetes lab
export LOCATION6=eastus2 #Reserved for the kubernetes lab
export START_ENV=0
export NBENV=2
